spring.application.name=rag

server.port=8081

# 1. Standard Spring Datasource (Local Java -> Docker Postgres)
spring.datasource.url=jdbc:postgresql://localhost:5433/incident_desk
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 3. local LLM via Ollama
langchain4j.ollama.chat-model.base-url=http://localhost:11434
langchain4j.ollama.chat-model.model-name=llama3.2:1b
langchain4j.ollama.embedding-model.base-url=http://localhost:11434
langchain4j.ollama.embedding-model.model-name=nomic-embed-text
#langchain4j.open-ai.chat-model.api-key=${OPENAI_API_KEY}
#langchain4j.open-ai.embedding-model.api-key=${OPENAI_API_KEY}
#langchain4j.open-ai.chat-model.model-name=gpt-4o
#langchain4j.open-ai.chat-model.temperature=0.0
#langchain4j.open-ai.embedding-model.model-name=text-embedding-3-small

# 4. LangChain4j - PgVector Embedding Store Config
# This connects the RAG logic to the Postgres instance
rag.pg.host=localhost
rag.pg.port=5433
rag.pg.database=incident_desk
rag.pg.user=user
rag.pg.password=password
rag.pg.table=documentation_chunks
langchain4j.pgvector.embedding-store.dimension=768

# 5. Enable RAG Auto-wiring
langchain4j.pgvector.embedding-store.create-table=true

# Instructs Spring Boot to import additional configuration properties from the .env file.
spring.config.import=optional:file:.env[.properties]

# run docker-compose at app start
spring.docker.compose.enabled=true
spring.docker.compose.file=docker-compose.yml
spring.docker.compose.lifecycle-management=start-only

# JWT
app.jwt.secret=${JWT.SECRET}
app.jwt.expiration-ms=${JWT.EXPIRATION}